# Generated by Django 4.2.1 on 2023-12-29 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("initialization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initialization",
            options={
                "verbose_name": "Initialization Completed Flag",
                "verbose_name_plural": "Initialization Completed Flag",
            },
        ),
    ]
