[tool.black]
target-version = ['py39']
extend-exclude = 'migrations'

[tool.isort]
profile = 'black'
skip = 'migrations'

[tool.mypy]
exclude = [
    'conreq/templates/.*',
    'migrations/.*',
]
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = 'conreq.settings'
