# Generated by Django 3.2.6 on 2021-08-28 19:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
import versionfield.fields


class Migration(migrations.Migration):

    replaces = [('app_store', '0001_initial'), ('app_store', '0002_auto_20210824_0100'), ('app_store', '0003_alter_app_sys_platforms'), ('app_store', '0004_alter_app_sys_platforms'), ('app_store', '0005_auto_20210824_0118'), ('app_store', '0006_auto_20210824_0123'), ('app_store', '0007_alter_app_sys_platforms'), ('app_store', '0008_auto_20210824_0136'), ('app_store', '0009_alter_apppackage_sys_platforms'), ('app_store', '0010_auto_20210828_1049'), ('app_store', '0011_auto_20210828_1133'), ('app_store', '0012_rename_url_screenshot_image'), ('app_store', '0013_envvar_default'), ('app_store', '0014_alter_apppackage_long_description'), ('app_store', '0015_auto_20210828_1156')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('default', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Environment Variable',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='app_store/screenshot/')),
            ],
        ),
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('development_stage', models.CharField(blank=True, choices=[('1 - Planning', 'Planning'), ('2 - Pre-Alpha', 'Pre-Alpha'), ('3 - Alpha', 'Alpha'), ('4 - Beta', 'Beta'), ('5 - Production/Stable', 'Stable'), ('6 - Mature', 'Mature'), ('7 - Inactive', 'Inactive')], max_length=21, null=True)),
                ('version', versionfield.fields.VersionField()),
                ('notice_message', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('repository_url', models.URLField(default='https://google.com')),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('donation_url', models.URLField(blank=True, null=True)),
                ('sys_platforms', multiselectfield.db.fields.MultiSelectField(choices=[('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=10)),
                ('touch_compatible', models.BooleanField()),
                ('mobile_compatible', models.BooleanField()),
                ('minimum_conreq_version', versionfield.fields.VersionField()),
                ('tested_conreq_version', versionfield.fields.VersionField()),
                ('max_conreq_version', versionfield.fields.VersionField(blank=True, null=True)),
                ('asynchronous', models.CharField(choices=[('NONE', 'No Async'), ('SEMI', 'Semi Async'), ('FULL', 'Fully Async')], max_length=20)),
                ('incompatible_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_incompatible_apps_+', to='app_store.AppPackage')),
                ('incompatible_categories', models.ManyToManyField(blank=True, related_name='incompatible_categories', to='app_store.Category')),
                ('incompatible_subcategories', models.ManyToManyField(blank=True, related_name='incompatible_subcategories', to='app_store.Subcategory')),
                ('optional_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_optional_apps_+', to='app_store.AppPackage')),
                ('required_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_required_apps_+', to='app_store.AppPackage')),
                ('subcategories', models.ManyToManyField(to='app_store.Subcategory')),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_type', models.CharField(default='GPLv3', max_length=100)),
                ('long_description', models.FileField(upload_to='app_store/readme/')),
                ('long_description_type', models.CharField(choices=[('text/plain', 'Plain Text (.txt)'), ('text/x-rst', 'reStructuredText (.rst)'), ('text/markdown', 'Markdown (.md)')], default='text/markdown', max_length=20)),
                ('package_name', models.CharField(default='dog', help_text='Must be snake_case.', max_length=100)),
                ('pypi_url', models.URLField(blank=True, null=True)),
                ('verbose_name', models.CharField(default='verbose_dog', max_length=100)),
                ('environment_variables', models.ManyToManyField(blank=True, to='app_store.EnvVar')),
                ('screenshots', models.ManyToManyField(blank=True, to='app_store.Screenshot')),
            ],
        ),
    ]
