# Generated by Django 3.2.7 on 2021-10-10 07:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
import versionfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(help_text='Must be snake_case.', max_length=100)),
                ('verbose_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('long_description', models.FileField(upload_to='app_store/readme/')),
                ('long_description_type', models.CharField(choices=[('text/plain', 'Plain Text (.txt)'), ('text/x-rst', 'reStructuredText (.rst)'), ('text/markdown', 'Markdown (.md)')], default='text/markdown', max_length=20)),
                ('development_stage', models.CharField(blank=True, choices=[('1 - Planning', 'Planning'), ('2 - Pre-Alpha', 'Pre-Alpha'), ('3 - Alpha', 'Alpha'), ('4 - Beta', 'Beta'), ('5 - Production/Stable', 'Stable'), ('6 - Mature', 'Mature'), ('7 - Inactive', 'Inactive')], max_length=21, null=True)),
                ('version', versionfield.fields.VersionField()),
                ('banner_message', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('repository_url', models.URLField()),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('donation_url', models.URLField(blank=True, null=True)),
                ('pypi_url', models.URLField(blank=True, null=True)),
                ('license_type', models.CharField(default='GPLv3', max_length=100)),
                ('sys_platforms', multiselectfield.db.fields.MultiSelectField(choices=[('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=10)),
                ('touch_compatible', models.BooleanField()),
                ('mobile_compatible', models.BooleanField()),
                ('minimum_conreq_version', versionfield.fields.VersionField()),
                ('tested_conreq_version', versionfield.fields.VersionField()),
                ('max_conreq_version', versionfield.fields.VersionField(blank=True, null=True)),
                ('asynchronous', models.CharField(choices=[('NONE', 'No Async'), ('SEMI', 'Semi Async'), ('FULL', 'Fully Async')], max_length=20)),
                ('incompatible_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_incompatible_apps_+', to='app_store.AppPackage')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='app_store/screenshot/')),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.apppackage')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeMessage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mark_read', models.BooleanField(blank=True, default=False, null=True)),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.apppackage')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(blank=True, default=False, null=True)),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.apppackage')),
            ],
        ),
        migrations.AddField(
            model_name='apppackage',
            name='incompatible_categories',
            field=models.ManyToManyField(blank=True, related_name='incompatible_categories', to='app_store.Category'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='incompatible_subcategories',
            field=models.ManyToManyField(blank=True, related_name='incompatible_subcategories', to='app_store.Subcategory'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='optional_apps',
            field=models.ManyToManyField(blank=True, related_name='_app_store_apppackage_optional_apps_+', to='app_store.AppPackage'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='required_apps',
            field=models.ManyToManyField(blank=True, related_name='_app_store_apppackage_required_apps_+', to='app_store.AppPackage'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='subcategories',
            field=models.ManyToManyField(to='app_store.Subcategory'),
        ),
    ]
