# Generated by Django 3.2.6 on 2021-08-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_squashed_0015_auto_20210828_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='package_name',
            field=models.CharField(help_text='Must be snake_case.', max_length=100),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='repository_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='verbose_name',
            field=models.CharField(max_length=100),
        ),
    ]
