# Generated by Django 3.2.6 on 2021-08-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_auto_20210828_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='environment_variables',
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='screenshots',
        ),
        migrations.DeleteModel(
            name='EnvVar',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
