# Generated by Django 4.0 on 2021-12-20 01:42

from django.db import migrations
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_remove_apppackage_incompatible_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppackage',
            name='conreq_minimum_version',
        ),
        migrations.AddField(
            model_name='apppackage',
            name='conreq_min_version',
            field=versionfield.fields.VersionField(default='0.0.0'),
        ),
    ]
