# Generated by Django 3.2.6 on 2021-08-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_auto_20210830_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppackage',
            old_name='banner',
            new_name='banner_message',
        ),
    ]
