# Generated by Django 3.2.6 on 2021-08-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_rename_banner_apppackage_banner_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='example',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='noticemessage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticemessage',
            name='mark_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
