"""Conreq's configuration values."""

# Startup
PRE_RUN = []
PRE_STARTUP = []
SETTING_SCRIPTS = []
INSTALLED_APPS = []
MIDDLEWARE = []
LANDING_TEMPLATE = ""
LANDING_VIEW = None
HOME_TEMPLATE = ""
HOME_VIEW = None
SIGN_UP_TEMPLATE = ""
SIGN_UP_VIEW = None
SIGN_IN_TEMPLATE = ""
SIGN_IN_VIEW = None
PASSWORD_RESET_TEMPLATE = ""
PASSWORD_RESET_VIEW = None

# ASGI
WEBSOCKETS = []

# WSGI
API_ENDPOINTS = []
URL_PATTERNS = []

# Components
NAVTABS = []
SERVER_SETTING_TABS = []
USER_SETTING_COMPONENTS = []

# HTML Head
CSS = []
SCSS = []
JAVASCRIPT = []
FONTS = []
HEAD_CONTENT = []
