# Generated by Django 3.2 on 2021-04-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='http_header_auth_user',
            new_name='externally_authenticated',
        ),
    ]
