# Generated by Django 3.1.5 on 2021-01-31 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
