# Generated by Django 3.1.5 on 2021-01-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conreqconfig',
            name='radarr_anime_folder',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='radarr_movies_folder',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='sonarr_anime_folder',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='sonarr_tv_folder',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
