# Generated by Django 3.1.5 on 2021-01-20 01:42

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0003_conreqconfig_conreq_initialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conreqconfig',
            name='conreq_secret_key',
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_app_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_app_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_custom_css',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_custom_js',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_language',
            field=models.CharField(default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='email_password',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='email_sender_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='email_smtp_server',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='email_username',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='radarr_api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='radarr_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='sonarr_api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='sonarr_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
