# Generated by Django 3.1.5 on 2021-02-06 07:43

import url_or_relative_url_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0010_auto_20210205_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_custom_css",
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_custom_js",
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(
                blank=True, default=""
            ),
        ),
    ]
