# Generated by Django 3.2.6 on 2021-08-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0020_auto_20210824_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conreqconfig',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
    ]
