# Generated by Django 3.2.7 on 2021-09-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0022_rename_conreqconfig_serverconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverconfig',
            options={'verbose_name': 'Server Settings', 'verbose_name_plural': 'Server Settings'},
        ),
    ]
