# Generated by Django 3.2.9 on 2021-11-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0023_alter_serverconfig_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serverconfig",
            options={
                "verbose_name": "Server settings",
                "verbose_name_plural": "Server settings",
            },
        ),
    ]
