# Generated by Django 4.0 on 2021-12-15 21:49

import conreq.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0032_alter_generalsettings_app_store_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='app_store_url',
            field=conreq.utils.fields.HostnameOrURLField(blank=True, help_text='Changes automatically on Conreq updates.'),
        ),
    ]
