# Generated by Django 4.0 on 2021-12-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0034_alter_generalsettings_server_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stylingsettings",
            name="initialized",
        ),
    ]
