# Generated by Django 4.0 on 2021-12-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0036_remove_generalsettings_initialized"),
    ]

    operations = [
        migrations.AddField(
            model_name="webserversettings",
            name="base_url",
            field=models.CharField(
                blank=True,
                help_text="Appears in all links (ex. example.com/base-url).",
                max_length=255,
            ),
        ),
    ]
