# Generated by Django 4.0.1 on 2022-01-06 19:18

from django.db import migrations, models

import conreq.app.fields


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0037_delete_webserversettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="app_store_url",
            field=conreq.app.fields.HostnameOrURLField(
                blank=True,
                help_text="Changes automatically on Conreq updates.",
                verbose_name="App store URL",
            ),
        ),
        migrations.AlterField(
            model_name="stylingsettings",
            name="custom_css",
            field=models.TextField(
                blank=True, default="", verbose_name="Custom JavaScript"
            ),
        ),
        migrations.AlterField(
            model_name="stylingsettings",
            name="custom_css_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Custom CSS URL"
            ),
        ),
        migrations.AlterField(
            model_name="stylingsettings",
            name="custom_js",
            field=models.TextField(blank=True, default="", verbose_name="Custom CSS"),
        ),
        migrations.AlterField(
            model_name="stylingsettings",
            name="custom_js_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Custom JavaScript URL"
            ),
        ),
    ]
