# Generated by Django 3.1.7 on 2021-04-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="http_header_auth_user",
            field=models.BooleanField(default=False),
        ),
    ]
