# Generated by Django 3.2.9 on 2021-11-16 13:41

import conreq.utils.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_users', '0004_rename_http_header_auth_user_profile_externally_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=conreq.utils.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
