name: Bug Report
description: Report a bug with Conreq software.
labels: [Bug]
body:
    - type: input
      attributes:
          label: Conreq Version
          description: What version did you encounter this issue on?
          placeholder: For example, v0.15.2
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Conreq Branch
          options:
              - Latest / Main
              - Develop
              - Other
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Server Operating System
          options:
              - Not Applicable
              - Windows
              - Linux
              - FreeBSD
              - MacOS
              - Other
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Client Operating System
          options:
              - Not Applicable
              - Windows
              - Linux
              - FreeBSD
              - MacOS
              - Android
              - iOS
              - Other
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Client Browser(s)
          multiple: true
          options:
              - Not Applicable
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - Other
      validations:
          required: false

    - type: textarea
      attributes:
          label: Description
      validations:
          required: true

    - type: textarea
      attributes:
          label: Log Info
          description: Copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
      validations:
          required: false
