# Generated by Django 3.2.9 on 2021-11-23 07:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_up", "0002_alter_invitecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=30, unique=True
            ),
        ),
    ]
