# Generated by Django 4.0 on 2022-01-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sign_up", "0003_alter_invitecode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="used_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.user",
            ),
        ),
    ]
