# Generated by Django 4.0.3 on 2022-04-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sign_up", "0005_alter_invitecode_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitecode",
            old_name="username",
            new_name="name",
        ),
    ]
