# Generated by Django 4.0.6 on 2022-07-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_up", "0006_rename_username_invitecode_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitecode",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
