# Generated by Django 4.1.3 on 2022-12-05 16:34

import conreq._core.sign_up.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sign_up", "0007_invitecode_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="expires_at",
            field=models.DateTimeField(default=conreq._core.sign_up.models._expiration),
        ),
    ]
