# Generated by Django 4.0 on 2021-12-15 19:44

import versionfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0002_alter_apppackage_incompatible_apps_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apppackage",
            old_name="description",
            new_name="short_description",
        ),
        migrations.RemoveField(
            model_name="apppackage",
            name="version",
        ),
        migrations.AddField(
            model_name="apppackage",
            name="min_version",
            field=versionfield.fields.VersionField(
                default="0.0.0",
                help_text="Minimum PyPI version or Git tag that is compatible with Conreq.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="banner_message",
            field=models.TextField(
                blank=True,
                help_text="Optional text message banner shown this apps details page.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="long_description",
            field=models.TextField(
                blank=True,
                help_text="This will be automatically fetched from PyPI or Git if left empty.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="package_name",
            field=models.CharField(
                help_text="Must be snake_case. Used for PyPI package installation, or folder naming on Git installations.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="repository_url",
            field=models.URLField(
                blank=True, help_text="Must be a Git repository if not using PyPI."
            ),
        ),
    ]
