# Generated by Django 4.0.1 on 2022-01-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0009_remove_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("name", "category")},
        ),
    ]
