# Generated by Django 4.0.1 on 2022-01-08 23:19

import conreq.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0011_alter_apppackage_logo_alter_screenshot_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to=conreq.utils.models.UUIDFilePath("serve/app_store/logos/"),
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=models.ImageField(
                upload_to=conreq.utils.models.UUIDFilePath(
                    "serve/app_store/screenshot/"
                )
            ),
        ),
    ]
