# Generated by Django 4.0.1 on 2022-01-24 16:33

from django.db import migrations
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0013_packageversion_apppackage_sync_with_pypi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='min_version',
            field=versionfield.fields.VersionField(default='0.0.0', help_text='Minimum PyPI version or Git tag for this package that is compatible with Conreq.'),
        ),
    ]
