# Generated by Django 4.0.2 on 2022-02-12 16:27

from django.db import migrations, models
import multiselectfield.db.fields
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0014_alter_apppackage_min_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='asynchronous',
            field=models.CharField(choices=[('NONE', 'No Async'), ('SEMI', 'Semi Async'), ('FULL', 'Fully Async')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='conreq_tested_version',
            field=versionfield.fields.VersionField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='development_stage',
            field=models.CharField(blank=True, choices=[('1 - Planning', 'Planning'), ('2 - Pre-Alpha', 'Pre-Alpha'), ('3 - Alpha', 'Alpha'), ('4 - Beta', 'Beta'), ('5 - Production/Stable', 'Stable'), ('6 - Mature', 'Mature'), ('7 - Inactive', 'Inactive')], default='1 - Planning', max_length=21),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='sys_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ANY', 'Any'), ('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], default='ANY', max_length=40, verbose_name='Supported Platforms'),
        ),
    ]
