# Generated by Django 4.0.2 on 2022-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0016_alter_apppackage_banner_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppackage',
            old_name='verbose_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apppackage',
            old_name='package_name',
            new_name='pkg_name',
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
