# Generated by Django 4.1 on 2022-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0017_rename_verbose_name_apppackage_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="pkg_name",
            field=models.CharField(
                help_text="Must be snake_case. Used for PyPI package installation, or folder naming on Git installations.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
