# Generated by Django 4.1.1 on 2022-10-13 15:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0018_alter_apppackage_pkg_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotlightCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("apps", models.ManyToManyField(to="app_store.apppackage")),
            ],
            options={
                "verbose_name": "Spotlight category",
                "verbose_name_plural": "Spotlight categories",
            },
        ),
    ]
