# Generated by Django 4.1.1 on 2022-10-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0020_remove_spotlightcategory_apps_spotlightthroughmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotlightcategory",
            name="apps",
            field=models.ManyToManyField(
                through="app_store.SpotlightThroughModel", to="app_store.apppackage"
            ),
        ),
    ]
