# Generated by Django 4.1.1 on 2022-10-13 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0022_spotlightcategory_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpotlightThroughModel",
            new_name="SpotlightApps",
        ),
    ]
