# Generated by Django 4.1.1 on 2022-10-13 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0024_rename_spotlightapps_spotlightapp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotlightcategory",
            name="apps",
        ),
        migrations.DeleteModel(
            name="SpotlightApp",
        ),
        migrations.DeleteModel(
            name="SpotlightCategory",
        ),
    ]
