# Generated by Django 4.1.1 on 2022-10-13 22:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_store",
            "0025_remove_spotlightcategory_apps_delete_spotlightapp_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotlightApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_store.apppackage",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "order"),
            },
        ),
        migrations.CreateModel(
            name="SpotlightCategory",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "apps",
                    models.ManyToManyField(
                        through="app_store.SpotlightApp", to="app_store.apppackage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spotlight category",
                "verbose_name_plural": "Spotlight categories",
            },
        ),
        migrations.AddField(
            model_name="spotlightapp",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_store.spotlightcategory",
            ),
        ),
    ]
