# Generated by Django 4.1.1 on 2022-10-18 14:49

import conreq.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0026_spotlightapp_spotlightcategory_spotlightapp_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppackage",
            name="background",
            field=models.ImageField(
                blank=True,
                upload_to=conreq.utils.models.UUIDFilePath(
                    "serve/app_store/backgrounds/"
                ),
            ),
        ),
    ]
