# Generated by Django 4.1.1 on 2022-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0027_apppackage_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppackage",
            name="special",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, this app's cards will be visually highlighted. Reserved for donations.",
            ),
        ),
    ]
