# Generated by Django 4.1.3 on 2022-12-06 18:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_store", "0028_apppackage_special"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppNoticeMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="banner_message",
            field=models.TextField(
                blank=True,
                help_text="Optional text message shown on the app info modal.",
                max_length=1000,
            ),
        ),
        migrations.DeleteModel(
            name="NoticeMessage",
        ),
        migrations.AddField(
            model_name="appnoticemessage",
            name="app_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_store.apppackage"
            ),
        ),
        migrations.AddField(
            model_name="appnoticemessage",
            name="read_by",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
