# Generated by Django 4.1.4 on 2023-01-02 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0032_category_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppackage",
            name="conreq_tested_version",
        ),
    ]
