# Generated by Django 4.1.4 on 2023-01-02 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0033_remove_apppackage_conreq_tested_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apppackage",
            old_name="optional_apps",
            new_name="related_apps",
        ),
    ]
