# Generated by Django 4.1.4 on 2023-01-02 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0034_rename_optional_apps_apppackage_related_apps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppackage",
            name="incompatible_subcategories",
        ),
    ]
