# Generated by Django 4.1.4 on 2023-01-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0036_alter_apppackage_asynchronous"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppackage",
            name="author_url",
            field=models.URLField(
                blank=True,
                help_text="This is typically a link to your GitHub user account or organization.",
            ),
        ),
    ]
