# Generated by Django 4.1.4 on 2023-01-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_store", "0037_apppackage_author_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
