# Generated by Django 4.1.5 on 2023-03-10 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0039_rename_spotlightapp_spotlightapppackages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "Categories"},
        ),
    ]
