# Generated by Django 4.1.5 on 2023-03-10 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0040_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotlightcategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Spotlight category",
                "verbose_name_plural": "Spotlight categories",
            },
        ),
    ]
