# Generated by Django 4.1.5 on 2023-03-10 09:52

from django.db import migrations
import ordered_model.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0041_alter_spotlightcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotlightcategory",
            name="apps",
            field=ordered_model.fields.OrderedManyToManyField(
                through="app_store.SpotlightAppPackages", to="app_store.apppackage"
            ),
        ),
    ]
