# Generated by Django 4.2.1 on 2023-12-29 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0043_pypidata_remove_apppackage_asynchronous_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apppackage",
            old_name="long_description",
            new_name="hidden_description",
        ),
    ]
