# Generated by Django 4.2.1 on 2023-12-29 01:15

import conreq._core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0044_rename_long_description_apppackage_hidden_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apppackage",
            old_name="custom_pip_install",
            new_name="custom_pip_install_command",
        ),
        migrations.RenameField(
            model_name="apppackage",
            old_name="min_version",
            new_name="package_min_version",
        ),
        migrations.RemoveField(
            model_name="apppackage",
            name="app_config_script",
        ),
        migrations.RemoveField(
            model_name="apppackage",
            name="developed",
        ),
        migrations.RemoveField(
            model_name="apppackage",
            name="pkg_name",
        ),
        migrations.AddField(
            model_name="apppackage",
            name="app_ready_script",
            field=conreq._core.fields.PythonTextField(
                blank=True,
                help_text="Python code that will be run after boot up. This code is run directly within the context of Conreq's `AppLoaderConfig.ready()` method. If you need revision control, create a dedicated `AppConfig` in your package release instead. Please note that this script will run once for each webserver worker.",
            ),
        ),
        migrations.AddField(
            model_name="apppackage",
            name="package_name",
            field=models.CharField(
                blank=True,
                help_text="Must be snake_case. Importable name within Python. If blank, it is a placeholder app.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="banner_message",
            field=models.TextField(
                blank=True,
                help_text="Optional text message shown on the app's details.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="donation_url",
            field=models.URLField(
                blank=True,
                help_text="Link where users can donate to this app's authors.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="hidden_description",
            field=models.TextField(
                blank=True,
                help_text="This description is only viewable within the database admin GUI.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="listed_on_pypi",
            field=models.BooleanField(
                default=False, help_text="Whether or not this app is listed on PyPI."
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="name",
            field=models.CharField(help_text="Human readable name.", max_length=100),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="pypi_name",
            field=models.CharField(
                blank=True,
                help_text="Name used for PyPI package installation. Defaults to `package_name` if left blank.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="settings_script",
            field=conreq._core.fields.PythonTextField(
                blank=True,
                help_text="Python code that will be run before boot up. This code is run directly within the context of Conreq's `settings.py`. If you need revision control, create a dedicated `conreq_settings.py` file in your package release instead.",
            ),
        ),
    ]
