# Generated by Django 4.2.1 on 2023-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_store",
            "0045_rename_custom_pip_install_apppackage_custom_pip_install_command_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="custom_pip_install_command",
            field=models.TextField(
                blank=True,
                help_text="Custom pip install command. If left blank, the default `pip install pypi_name` will be used.",
            ),
        ),
    ]
