# Generated by Django 4.2.1 on 2023-12-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0046_alter_apppackage_custom_pip_install_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="donation_url",
            field=models.URLField(
                blank=True,
                help_text="Link where users can donate to this app's author.",
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="package_name",
            field=models.CharField(
                blank=True,
                help_text="Importable name within Python. Must be snake_case.If blank, it is a placeholder app.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="special",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, this app's cards will be visually highlighted. Typically reserved for unique situations, such as authors who have donated to Conreq.",
            ),
        ),
    ]
