# Generated by Django 4.2.1 on 2023-12-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0047_alter_apppackage_donation_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppackage",
            name="package_name",
            field=models.CharField(
                blank=True,
                help_text="Importable name within Python. Must be snake_case. If blank, it is a placeholder app.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
