# Generated by Django 4.2.1 on 2023-12-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0048_alter_apppackage_package_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apppackage",
            name="listed_on_pypi",
        ),
        migrations.AlterField(
            model_name="apppackage",
            name="pypi_name",
            field=models.CharField(
                blank=True,
                help_text="Name used for PyPI package installation. Defaults to `package_name` if left blank. You can set this to N/A to indicate that this app is not listed on PyPI.",
                max_length=100,
            ),
        ),
    ]
