# Generated by Django 4.2.1 on 2023-12-29 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_store", "0049_remove_apppackage_listed_on_pypi_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pypidata",
            options={
                "verbose_name": "App PyPI data",
                "verbose_name_plural": "App PyPI data",
            },
        ),
    ]
