# Generated by Django 3.2 on 2021-04-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0016_alter_conreqconfig_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conreqconfig',
            name='conreq_dark_theme',
        ),
    ]
