# Generated by Django 3.1.5 on 2021-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='resolution',
            field=models.TextField(),
        ),
    ]
