# Generated by Django 3.1.5 on 2021-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0004_auto_20210203_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissue',
            name='episode_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportedissue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
