# Generated by Django 3.1.5 on 2021-02-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0006_auto_20210203_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='episode_numbers',
            new_name='episodes',
        ),
    ]
