# Generated by Django 3.1.5 on 2021-02-06 08:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0008_auto_20210206_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='episode_ids',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='episodes',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='issues',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='seasons',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
