# Generated by Django 3.2 on 2021-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0009_auto_20210206_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
