# Generated by Django 3.1.3 on 2021-01-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConreqConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('app_logo', models.ImageField(upload_to='')),
                ('app_url', models.URLField()),
                ('custom_css', models.TextField()),
                ('simple_posters', models.BooleanField()),
                ('debug_mode', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.URLField()),
                ('smtp_port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=50)),
                ('enable_tls', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadarrConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
                ('anime_quality_profile', models.PositiveIntegerField()),
                ('anime_folder', models.FilePathField()),
                ('movie_quality_profile', models.PositiveIntegerField()),
                ('enable_ssl', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SonarrConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
                ('anime_quality_profile', models.PositiveIntegerField()),
                ('anime_folder', models.FilePathField()),
                ('series_quality_profile', models.PositiveIntegerField()),
                ('enable_ssl', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
