# Generated by Django 3.1.3 on 2021-01-08 06:32

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='username',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
    ]
