# Generated by Django 3.1.5 on 2021-01-13 04:11

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210107_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radarrconfig',
            name='enable_ssl',
        ),
        migrations.RemoveField(
            model_name='sonarrconfig',
            name='enable_ssl',
        ),
        migrations.RemoveField(
            model_name='sonarrconfig',
            name='series_quality_profile',
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='radarrconfig',
            name='movie_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='sonarrconfig',
            name='tv_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='sonarrconfig',
            name='tv_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='app_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='app_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='base_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='custom_css',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='secret_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='simple_posters',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='enable_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='sender_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_server',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='username',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='radarrconfig',
            name='anime_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='radarrconfig',
            name='anime_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='radarrconfig',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='radarrconfig',
            name='movie_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='radarrconfig',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='sonarrconfig',
            name='anime_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='sonarrconfig',
            name='anime_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sonarrconfig',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sonarrconfig',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
