# Generated by Django 3.1.5 on 2021-01-13 04:28

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210112_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfig',
        ),
        migrations.DeleteModel(
            name='RadarrConfig',
        ),
        migrations.DeleteModel(
            name='SonarrConfig',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='api_key',
            new_name='conreq_api_key',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='app_logo',
            new_name='conreq_app_logo',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='app_name',
            new_name='conreq_app_name',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='app_url',
            new_name='conreq_app_url',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='base_url',
            new_name='conreq_base_url',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='custom_css',
            new_name='conreq_custom_css',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='language',
            new_name='conreq_language',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='secret_key',
            new_name='conreq_secret_key',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='simple_posters',
            new_name='conreq_simple_posters',
        ),
        migrations.RemoveField(
            model_name='conreqconfig',
            name='debug_mode',
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_enable_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_password',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_sender_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_smtp_server',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='email_username',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_anime_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_anime_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_movie_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_movie_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_anime_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_anime_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_tv_folder',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_tv_quality_profile',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_url',
            field=models.URLField(default=''),
        ),
    ]
