# Generated by Django 3.1.5 on 2021-01-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210112_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='conreqconfig',
            name='radarr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='sonarr_season_folders',
            field=models.BooleanField(default=True),
        ),
    ]
