# Generated by Django 3.1.5 on 2021-01-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20210112_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='conreqconfig',
            name='conreq_auto_resolve_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='conreq_guest_login',
            field=models.BooleanField(default=False),
        ),
    ]
