# Generated by Django 3.1.5 on 2021-01-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20210112_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='radarr_movie_folder',
            new_name='radarr_movies_folder',
        ),
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='radarr_movie_quality_profile',
            new_name='radarr_movies_quality_profile',
        ),
    ]
