# Generated by Django 3.1.5 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20210113_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='conreqconfig',
            name='conreq_custom_javascript',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='conreqconfig',
            name='conreq_dark_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_app_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_custom_css',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='email_smtp_server',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='radarr_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='conreqconfig',
            name='sonarr_url',
            field=models.URLField(default=''),
        ),
    ]
