# Generated by Django 3.1.5 on 2021-01-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20210113_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conreqconfig',
            old_name='conreq_custom_javascript',
            new_name='conreq_custom_js',
        ),
    ]
