# Generated by Django 3.1.5 on 2021-01-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20210113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conreqconfig',
            name='conreq_app_name',
            field=models.CharField(default='Conreq', max_length=100),
        ),
    ]
