# Generated by Django 3.1.5 on 2021-01-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20210115_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conreqconfig',
            name='conreq_base_url',
        ),
    ]
