# Generated by Django 3.1.5 on 2021-02-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0002_auto_20210203_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='reportedissue',
            old_name='resolution',
            new_name='resolutions',
        ),
    ]
