# Generated by Django 3.1.5 on 2021-02-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0003_auto_20210203_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='names',
            new_name='issues',
        ),
    ]
