# Generated by Django 3.1.5 on 2021-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0005_auto_20210203_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='episode_ids',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='episode_numbers',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='seasons',
            field=models.TextField(default='[]'),
        ),
    ]
