# Generated by Django 3.2.4 on 2021-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0010_alter_reportedissue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='resolved',
            new_name='manually_resolved',
        ),
        migrations.AddField(
            model_name='reportedissue',
            name='auto_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
