# Generated by Django 3.2.4 on 2021-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0011_auto_20210621_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='manually_resolved',
            new_name='resolved',
        ),
    ]
