# Generated by Django 3.2.5 on 2021-07-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0012_rename_manually_resolved_reportedissue_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedissue',
            name='resolutions',
        ),
    ]
