# Generated by Django 3.2.5 on 2021-07-06 05:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0013_remove_reportedissue_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissue',
            name='resolutions',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
