# Generated by Django 3.2.5 on 2021-07-06 05:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0014_reportedissue_resolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='episode_ids',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='episodes',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='seasons',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
