# Generated by Django 3.2.5 on 2021-07-06 05:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0015_auto_20210705_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='episode_ids',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='episodes',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='seasons',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
