# Generated by Django 3.2.5 on 2021-07-06 09:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0017_remove_reportedissue_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='resolutions',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
