# Generated by Django 3.2.5 on 2021-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_reporting', '0018_alter_reportedissue_resolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissue',
            name='auto_resolve_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
