# Generated by Django 3.2.9 on 2021-11-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email", "0002_alter_emailconfig_smtp_server"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailconfig",
            old_name="smtp_port",
            new_name="port",
        ),
        migrations.RenameField(
            model_name="emailconfig",
            old_name="smtp_server",
            new_name="server",
        ),
    ]
