# Generated by Django 3.2.9 on 2021-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_auto_20211119_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='timeout',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
