# Generated by Django 4.0 on 2021-12-18 17:07

import conreq.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0006_alter_emailconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='password',
            field=conreq.utils.fields.PasswordField(blank=True, default='', max_length=255),
        ),
    ]
