# Generated by Django 4.0 on 2022-01-02 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_alter_invitecode_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
