# Generated by Django 3.1.5 on 2021-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0006_auto_20210130_0236"),
    ]

    operations = [
        migrations.AddField(
            model_name="conreqconfig",
            name="conreq_http_header_auth",
            field=models.BooleanField(default=False),
        ),
    ]
