# Generated by Django 3.1.5 on 2021-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_settings", "0007_conreqconfig_conreq_http_header_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_simple_posters",
            field=models.BooleanField(default=True),
        ),
    ]
