# Generated by Django 3.1.5 on 2021-02-06 07:43

from django.db import migrations
from django.db.models.fields import URLField


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0010_auto_20210205_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_custom_css",
            field=URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_custom_js",
            field=URLField(blank=True, default=""),
        ),
    ]
