# Generated by Django 3.1.5 on 2021-02-10 05:44

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_settings", "0011_auto_20210205_2343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conreqconfig",
            name="conreq_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="email_password",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="email_username",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="radarr_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="conreqconfig",
            name="sonarr_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
