# Generated by Django 3.1.7 on 2021-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_settings", "0012_auto_20210209_2144"),
    ]

    operations = [
        migrations.AddField(
            model_name="conreqconfig",
            name="conreq_allow_tv_specials",
            field=models.BooleanField(default=True),
        ),
    ]
