# Generated by Django 3.1.7 on 2021-03-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0014_auto_20210313_0231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conreqconfig",
            name="conreq_app_name",
        ),
    ]
