# Generated by Django 3.2.2 on 2021-05-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0018_auto_20210428_2039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conreqconfig",
            name="conreq_api_key",
        ),
    ]
