# Generated by Django 3.2.6 on 2021-08-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0021_alter_conreqconfig_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConreqConfig",
            new_name="ServerConfig",
        ),
    ]
