# Generated by Django 4.0.1 on 2022-01-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_settings", "0036_remove_generalsettings_initialized"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebserverSettings",
        ),
    ]
