# Generated by Django 4.0.6 on 2022-07-29 02:11

import conreq._core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_settings', '0047_alter_generalsettings_app_store_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='app_store_url',
            field=conreq._core.fields.HostnameOrURLField(blank=True, help_text='Set this to override the default app store.', verbose_name='App store URL'),
        ),
    ]
