# Generated by Django 4.2 on 2023-05-04 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server_settings", "0048_alter_generalsettings_app_store_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalsettings",
            name="app_store_url",
        ),
    ]
