# Generated by Django 3.2.2 on 2021-05-09 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_requests', '0003_alter_userrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
