# Generated by Django 3.2.6 on 2021-08-24 08:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_auto_20210824_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sys_platforms',
            field=multiselectfield.db.fields.MultiSelectField(max_length=10, verbose_name=(('ANY', 'any'), ('AIX', 'aix'), ('LINUX', 'linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'cygwin'), ('MACOS', 'darwin'))),
        ),
    ]
