# Generated by Django 3.2.6 on 2021-08-30 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_auto_20210829_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='app_store/screenshot/')),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.apppackage')),
            ],
        ),
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('app_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.apppackage')),
            ],
            options={
                'verbose_name': 'Environment Variable',
            },
        ),
    ]
