# Generated by Django 3.2.6 on 2021-08-24 08:18

from django.db import migrations
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_app_sys_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='environment_variables',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='app',
            name='screenshots',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='app',
            name='sys_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ANY', 'any'), ('AIX', 'aix'), ('LINUX', 'linux'), ('WINDOWS', 'windows'), ('CYGWIN', 'cygwin'), ('MACOS', 'darwin')], max_length=10),
        ),
    ]
