# Generated by Django 3.2.6 on 2021-08-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_auto_20210824_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='development_stage',
            field=models.CharField(blank=True, choices=[('PREALPHA', 'Pre-Alpha'), ('ALPHA', 'Alpha'), ('BETA', 'Beta'), ('STABLE', 'Stable'), ('DEPRECATED', 'Deprecated'), ('OBSOLETE', 'Obsolete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='donation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='notice_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='support_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
