# Generated by Django 3.2.6 on 2021-08-24 08:36

from django.db import migrations, models
import jsonfield.fields
import multiselectfield.db.fields
import uuid
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_alter_app_sys_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('development_stage', models.CharField(blank=True, choices=[('PREALPHA', 'Pre-Alpha'), ('ALPHA', 'Alpha'), ('BETA', 'Beta'), ('STABLE', 'Stable'), ('DEPRECATED', 'Deprecated'), ('OBSOLETE', 'Obsolete')], max_length=20, null=True)),
                ('version', versionfield.fields.VersionField()),
                ('screenshots', jsonfield.fields.JSONField(blank=True, default=[])),
                ('notice_message', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('donation_url', models.URLField(blank=True, null=True)),
                ('environment_variables', jsonfield.fields.JSONField(blank=True, default=[])),
                ('sys_platforms', multiselectfield.db.fields.MultiSelectField(choices=[('ANY', 'Any'), ('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=10)),
                ('touch_compatible', models.BooleanField()),
                ('mobile_compatible', models.BooleanField()),
                ('minimum_conreq_version', versionfield.fields.VersionField()),
                ('tested_conreq_version', versionfield.fields.VersionField()),
                ('max_conreq_version', versionfield.fields.VersionField(blank=True, null=True)),
                ('asynchronous', models.CharField(choices=[('NONE', 'No Async'), ('SEMI', 'Semi Async'), ('FULL', 'Fully Async')], max_length=20)),
                ('incompatible_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_incompatible_apps_+', to='app_store.AppPackage')),
                ('incompatible_categories', models.ManyToManyField(blank=True, related_name='incompatible_categories', to='app_store.Category')),
                ('incompatible_subcategories', models.ManyToManyField(blank=True, related_name='incompatible_subcategories', to='app_store.Subcategory')),
                ('optional_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_optional_apps_+', to='app_store.AppPackage')),
                ('required_apps', models.ManyToManyField(blank=True, related_name='_app_store_apppackage_required_apps_+', to='app_store.AppPackage')),
                ('subcategories', models.ManyToManyField(to='app_store.Subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
