# Generated by Django 3.2.6 on 2021-08-24 08:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0008_auto_20210824_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='sys_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AIX', 'Aix'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('CYGWIN', 'Cygwin'), ('MACOS', 'Darwin')], max_length=10),
        ),
    ]
