# Generated by Django 3.2.6 on 2021-08-28 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_alter_apppackage_sys_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('example', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='name',
        ),
        migrations.AddField(
            model_name='apppackage',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='license',
            field=models.CharField(default='GPLv3', max_length=100),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='long_description_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text (.txt)'), ('text/x-rst', 'reStructuredText (.rst)'), ('text/markdown', 'Markdown (.md)')], default='text/markdown', max_length=20),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='package_name',
            field=models.CharField(default='dog', help_text='Must be snake_case.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apppackage',
            name='pypi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='verbose_name',
            field=models.CharField(default='verbose_dog', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='development_stage',
            field=models.CharField(blank=True, choices=[('1 - Planning', 'Planning'), ('2 - Pre-Alpha', 'Pre-Alpha'), ('3 - Alpha', 'Alpha'), ('4 - Beta', 'Beta'), ('5 - Production/Stable', 'Stable'), ('6 - Mature', 'Mature'), ('7 - Inactive', 'Inactive')], max_length=21, null=True),
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='environment_variables',
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='repository_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='apppackage',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='apppackage',
            name='environment_variables',
            field=models.ManyToManyField(blank=True, to='app_store.EnvVar'),
        ),
        migrations.AddField(
            model_name='apppackage',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='app_store.Screenshot'),
        ),
    ]
