# Generated by Django 3.2.6 on 2021-08-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0010_auto_20210828_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envvar',
            options={'verbose_name': 'Environment Variable'},
        ),
        migrations.RenameField(
            model_name='apppackage',
            old_name='license',
            new_name='license_type',
        ),
    ]
