# Generated by Django 3.2.6 on 2021-08-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0011_auto_20210828_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='url',
            new_name='image',
        ),
    ]
