# Generated by Django 3.2.6 on 2021-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0012_rename_url_screenshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvar',
            name='default',
            field=models.CharField(default='', max_length=255),
        ),
    ]
