# Generated by Django 3.2.6 on 2021-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0013_envvar_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='long_description',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
