# Generated by Django 3.2.6 on 2021-08-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0014_alter_apppackage_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackage',
            name='long_description',
            field=models.FileField(upload_to='app_store/readme/'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='app_store/screenshot/'),
        ),
    ]
