# Generated by Django 3.2.7 on 2021-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_server",
            field=models.CharField(default="smtp.gmail.com", max_length=255),
        ),
    ]
