# Generated by Django 4.0 on 2021-12-28 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0007_alter_emailconfig_password"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailConfig",
            new_name="EmailSettings",
        ),
    ]
