---
name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - ["main", "develop"]
    schedule:
        - cron: "0 0 * * *"

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - run: pip install -r requirements/docs.txt
            - run: mkdocs build --verbose
